orbs:
  slack: circleci/slack@3.4.2
version: 2.1

jobs:
  run-tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Build docker images"
          command: docker-compose -f compose/docker-compose-test.yml build
      - run:
          name: "Run app in docker"
          command: |
            docker-compose -f compose/docker-compose-test.yml up -d
            sleep 3
            docker-compose -f compose/docker-compose-test.yml exec adminpanel python manage.py makemigrations
            docker-compose -f compose/docker-compose-test.yml exec adminpanel python manage.py migrate
      - run:
          name: "Run tests"
          command: docker-compose -f compose/docker-compose-test.yml exec adminpanel pytest
      - slack/status:
            success_message: '[$CIRCLE_BRANCH] $CIRCLE_USERNAME started a job $CIRCLE_JOB.
              
              Status: pass ✅ '
            failure_message: '[$CIRCLE_BRANCH] $CIRCLE_USERNAME started a job $CIRCLE_JOB.
              
              Status: fail ❌'
#           fail_only: true
#           only_for_branches: 'master,development'
workflows:
   version: 2
   main:
     jobs:
       - run-tests
