apiVersion: 1

deleteDatasources:
  - name: SportPostgres
    orgId: 1

datasources:
  - name: SportPostgres
    type: postgres
    url: ${POSTGRES_SERVER}:5432
    database: ${POSTGRES_DB}
    user: ${GRAFANA_DB_USER}
    secureJsonData:
      password: ${GRAFANA_DB_USER_PASSWORD}
    jsonData:
      sslmode: "disable"
      postgresVersion: 1100
      timescaledb: false