version: '3.5'
services:
  nginx:
    restart: always
    build:
      context: ../nginx
    ports:
      - "81:80"
    depends_on:
      - adminpanel
      - adminer
    volumes:
      - ../nginx/logs:/var/log/nginx
      - ../nginx/access.d:/etc/nginx/access.d
      - django-static:/static

  adminpanel:
    build:
      context: ../adminpage
      dockerfile: Dockerfile
      args:
        - PYTHON_DOCKER_VERSION
    #   Wait for postgres to startup before running server
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn adminpage.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --lifespan off --proxy-headers'
    restart: always
    volumes:
      - django-auth-preserve:/usr/local/lib/python${PYTHON_DOCKER_VERSION}/site-packages/django/contrib/auth/migrations/
      - django-static:/static
      - /sport/media:/uploaded_media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: db
    build:
      context: ..
      dockerfile: Dockerfile.db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env


  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "8081:8080"


volumes:
  db-data:
  django-static:
  # required to preserve change to django.contrib.auth.models.Group class.
  # (verbose_name added)
  # since Innopolis adfs provides groupsid as universal identifier
  # (group - can be either in Russian or English)
  django-auth-preserve:
  uploaded_media:
