name: Staging deploy
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Tests"]
    types:
      - completed
jobs:
  deploy:
    name: Deploy to staging server
    runs-on: self-hosted
    environment:
      name: new-sport-env
      url: https://new.sport.innopolis.university
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Deploy via Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: start.yml
          directory: ./ansible
